/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SldtestRouteImport } from './routes/sldtest'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiPublicWaInvoiceRouteImport } from './routes/api/public/wa-invoice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SldtestRoute = SldtestRouteImport.update({
  id: '/sldtest',
  path: '/sldtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaInvoiceRoute = ApiPublicWaInvoiceRouteImport.update({
  id: '/api/public/wa-invoice',
  path: '/api/public/wa-invoice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sldtest': typeof SldtestRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/wa-invoice': typeof ApiPublicWaInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sldtest': typeof SldtestRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/wa-invoice': typeof ApiPublicWaInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sldtest': typeof SldtestRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/wa-invoice': typeof ApiPublicWaInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sldtest' | '/api/tts' | '/api/public/wa-invoice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sldtest' | '/api/tts' | '/api/public/wa-invoice'
  id: '__root__' | '/' | '/sldtest' | '/api/tts' | '/api/public/wa-invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SldtestRoute: typeof SldtestRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicWaInvoiceRoute: typeof ApiPublicWaInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sldtest': {
      id: '/sldtest'
      path: '/sldtest'
      fullPath: '/sldtest'
      preLoaderRoute: typeof SldtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa-invoice': {
      id: '/api/public/wa-invoice'
      path: '/api/public/wa-invoice'
      fullPath: '/api/public/wa-invoice'
      preLoaderRoute: typeof ApiPublicWaInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SldtestRoute: SldtestRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicWaInvoiceRoute: ApiPublicWaInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
